In [15]:
# - Descriptive Statistics
import pandas as pd
import numpy as np

In [17]:
data = {
    'A': [32, 12, 54],
    'B': [21, 34, 65],
    'C': [75, 32, 43],
    'D': [76, 65, 53],
    'E': [13, 43, 34]
}

In [19]:
type(data)

dict

In [21]:
df = pd.DataFrame(data)

In [23]:
df

A   B   C   D   E
0  32  21  75  76  13
1  12  34  32  65  43
2  54  65  43  53  34

In [25]:
# Flatten the data values into list
values = []
for col in data.values():
    values.extend(col)

# now reshape into 5 col and 3 rows
reshaped_array = np.array(values).reshape(5, 3)
print(reshaped_array)

[[32 12 54]
 [21 34 65]
 [75 32 43]
 [76 65 53]
 [13 43 34]]


In [27]:
df = pd.DataFrame(reshaped_array)

In [29]:
df

0   1   2
0  32  12  54
1  21  34  65
2  75  32  43
3  76  65  53
4  13  43  34

In [31]:
df.mean()

0    43.4
1    37.2
2    49.8
dtype: float64

In [33]:
df.max()

0    76
1    65
2    65
dtype: int32

In [35]:
df.min()

0    13
1    12
2    34
dtype: int32

In [37]:
df.median()

0    32.0
1    34.0
2    53.0
dtype: float64

In [39]:
df.std()

0    30.071581
1    19.227584
2    11.777096
dtype: float64

In [41]:
df.describe()

0          1          2
count   5.000000   5.000000   5.000000
mean   43.400000  37.200000  49.800000
std    30.071581  19.227584  11.777096
min    13.000000  12.000000  34.000000
25%    21.000000  32.000000  43.000000
50%    32.000000  34.000000  53.000000
75%    75.000000  43.000000  54.000000
max    76.000000  65.000000  65.000000